services:
  tikz-server:
    image: ghcr.io/skafis-edtech/matikzy-render-i:latest
    build: .
    container_name: tikz-server
    ports:
      - "3001:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save ""
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - redis-tikz:/data

volumes:
  redis-tikz:
